### ISSUE TITLE
What list/stream on Twitter is being analyzed?

### ISSUE THREAD

**Issue by sedemmler** [uclatommy/tweetfeels#20]
Is it everyone followed by, for example, my account? Or is it a specific word on all of Twitter? Can I designate a specifically created Twitter list?

**Comment by uclatommy** [comment]
It's the public twitter feed (all tweets). You provide a list of keywords you are tracking and any matches will get saved to the database. The sentiment calculation uses this saved data to provide a sentiment score. For example, this will save all public tweets that matching keyword "trump":
```python
trump_feels = TweetFeels(login, tracking=['trump'])
```
You can set your own list of keywords however you want, but currently it all goes into one database and gets mixed into a single sentiment score. You should be able to track different things and keep them separate after I'm done with #5 .

**Comment by sedemmler** [comment]
Thanks, Tommy.
