### ISSUE TITLE
UnboundLocalError: local variable 's' referenced before assignment

### ISSUE THREAD

**Issue by tluyben** [uclatommy/tweetfeels#35]
In tweetfeels.py I always get this error  on the 

return s

There is data (I can print it and there are many tweets with the subjects i'm looking at) and sentiments is a generator returned, but it never gives a next. What could be wrong?

**Comment by tluyben** [comment]
Think I found the answer; you need to unzip and manually copy the vader lexicon txt file into your working directory if you are under Windows, otherwise the sentiment is always 0 and it throws those away.

**Comment by uclatommy** [comment]
Thanks for reporting and testing. I am currently traveling so don't have windows machine readily available to test. However, feel free to send a pull request if you end up making any changes.

-Thomas

**Comment by DhavalThkkar** [comment]
I have this error in Ubuntu. Whenever I try to run `trump_feels.sentiment.values` I always get `UnboundLocalError: local variable 's' referenced before assignment `.
