### ISSUE TITLE
Sentiment Score: 0

### ISSUE THREAD

**Issue by jasperdew** [uclatommy/tweetfeels#40]
Hi,
really cool project!
However, I'm having the issue that I continue to get "Sentiment Score: 0" for the Trump example. Considering the volume of this keyword and the fact that it's Trump, I can't imagine 0 is right;-)

I've followed exactly the steps described and everything went smoothly for the rest. Any idea what might be wrong?

**Comment by uclatommy** [comment]
I would start by taking a look inside the sqlite database you are saving the tweets into. There are third party apps that allow you browse the file easily through a gui. I suspect that there is something wrong and no tweets are being saved into it. Perhaps a write permissions problem in the directory where you are running the script from?
