### ISSUE TITLE
Counting Tweets

### ISSUE THREAD

**Issue by StrazzaD** [uclatommy/tweetfeels#42]
Hi uclatommy,
compliments for this project, it's awesome.

Is there some function to count the tweets analyzed?

Thx,
Marco

**Comment by uclatommy** [comment]
You can find the number of tweets in the db (and therefore being analyzed) like so:
```
len(trump_feels._feels.all)
```

Or you can find the number of tweets between certain dates like so:
```
len(trump_feels._feels.tweets_between(start, end).df)
```
where start and end are `datetimes`s
