### ISSUE TITLE
Issue with setup

### ISSUE THREAD

**Issue by Muggsie** [uclatommy/tweetfeels#45]
![screen shot 2018-11-09 at 19 10 29](https://user-images.githubusercontent.com/42708283/48297223-3a7ddd80-e4de-11e8-8857-de71a03cb0c2.png)

What am I doing wrong here? 

Have installed and updated all required packages per the readme file. 

Python 3.7.1
macOS high sierra 10.13.1

**Comment by uclatommy** [comment]
This is a problem with tweepy on python 3.7. You can find more details about it here: https://github.com/tweepy/tweepy/issues/1017. This won't get fixed until tweepy pushes out a new version that works with python 3.7.

**Comment by uclatommy** [comment]
I decided to change the requirements to peg tweepy to their latest master copy instead of waiting for them to release since they already had a fix in but haven't released for a year. I'll package a release soon, but for now, you can fix your issue by:
```
pip uninstall tweepy
pip install -U git+https://github.com/tweepy/tweepy.git@2efe385fc69385b57733f747ee62e6be12a1338b
```

**Comment by StayFoolisj** [comment]
This did it! Thanks for helping out. Time to have fun
