### ISSUE TITLE
TypeError: filter() got an unexpected keyword argument 'is_async'

### ISSUE THREAD

**Issue by windowshopr** [uclatommy/tweetfeels#50]
What am I missing here? Running Python 3.6 on Windows 10 with the following script (login tokens blanked out):

from tweetfeels import TweetFeels
from threading import Thread
import time

consumer_key = "***************************"
consumer_secret = "********************************"
access_token = "***********************************"
access_token_secret = "*********************************"
login = [consumer_key, consumer_secret, access_token, access_token_secret]

trump_feels = TweetFeels(login, tracking=['trump'])
trump_feels.start(10)
trump_feels.sentiment.value

..... and receiving the following error:

Traceback (most recent call last):
  File "script.py", line 14, in <module>
    trump_feels.start(10)
  File "C:\Users\...\Python\Python36\lib\site-packages\tweetfeels\tweetfeels.py", line 160, in start
    filter_level=self._filter_level
TypeError: filter() got an unexpected keyword argument 'is_async'

Before I start messing with the tweetfeels files, anyone have any idea? Thanks.

**Comment by windowshopr** [comment]
I spoke too soon. Was missing the nose dependency.

**Comment by ngeorgj** [comment]
dude you saved my life.
